### ISSUE TITLE
document l compat flag

### ISSUE THREAD

**Issue by abma** [spring/LobbyProtocol#35]
not sure if this should be enabled globally, in battle only or only in channels & battles.

easiest solution would be to add a compatiblity flag

and replace cpuid from ADDUSER with the lobby version

ideally change to named vars when doing this change

**Comment by abma** [comment]
https://github.com/spring/uberserver/commit/024c1c6b230d9612746e6b5b3a641a5cd0ed4c64

**Comment by silentwings** [comment]
done
