### ISSUE TITLE
LobbyID in AddUser command is not indicated as a sentence

### ISSUE THREAD

**Issue by MasterBel2** [spring/LobbyProtocol#43]
<img width="188" alt="image" src="https://user-images.githubusercontent.com/39206414/68605225-c1053a80-04f7-11ea-9afd-a25da1cf2f65.png">
Minor issue, but if you're expecting this to be a sentence, you'll parse it incorrectly. Description currently says it's not:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/39206414/68605378-0590d600-04f8-11ea-8ce9-231db86b72dd.png">

Let me know how this repo works (do I just change the XML file?) and I'll create a PR for this and all future issues to save you time instead.

Regards,
~MasterBel2

**Comment by MasterBel2** [comment]
Related: No lobby ID is sent through for ChanServ. Should this be noted in the argument description, fixed in Uberserver, or which?

**Comment by abma** [comment]
> do I just change the XML file?

yes.

i guess you are referring https://github.com/spring/LobbyProtocol/blob/master/ProtocolDescription.xml#L925 ?

atm it seems to be "the rest of the string" and not a sentence:

https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L739

**Comment by MasterBel2** [comment]
Being "the rest of the string" seems to fit the description of a sentence. See protocol description: 
<img width="748" alt="image" src="https://user-images.githubusercontent.com/39206414/68640482-9cd74700-0553-11ea-846f-ad045a6fa11f.png">

Moreover, all other commands I've come across with "rest of the string" is 
<img width="136" alt="image" src="https://user-images.githubusercontent.com/39206414/68640541-e45dd300-0553-11ea-9832-a24e0038b0e9.png">
<img width="134" alt="image" src="https://user-images.githubusercontent.com/39206414/68640572-f2abef00-0553-11ea-8f47-250cff182ffc.png">

Is there some hidden difference between a sentence and "the rest of the string"? If so, can this distinction be removed?

**Comment by MasterBel2** [comment]
Looking at uberserver's implementation, "the rest of the string" seems to be synonymous with a sentence, unless it's explicitely a word?
