### ISSUE TITLE
CPU argument for ADDUSER doesn't seem to exist

### ISSUE THREAD

**Issue by MasterBel2** [spring/LobbyProtocol#44]
Is it hidden behind a comp flag, not sent by the lobbies so the server doesn't have it, or just not sent by the server at all? For now, I'll just assume it doesn't exist at all anymore.

**Comment by abma** [comment]
cpu argument is deprecated and shouldn't be used or ignored:

https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L952

**Comment by abma** [comment]
not sure what you mean, this is relevant, too:

https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L736
